=== iamabhijeet2003/DAW/1-DAW/LMI/XSD/XSD3.7/ejercicio5xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento" maxOccurs="unbounded"> 
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="comentario" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto" type="elementos" maxOccurs="unbounded"/>
                        </xs:sequence>
                       
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="elementos">
        <xs:sequence>
            <xs:element name ="nombre" type="xs:string"/>
            <xs:element name="precio">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                            <xs:attribute name="moneda" use="optional" type="xs:string"/>
                            <xs:attribute name="descuento" default="no">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="si"/>
                                        <xs:enumeration value="no"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== iamabhijeet2003/DAW/1-DAW/LMI/XSD/XSD3.7/ejercicio5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio5xsd.xsd">
    <departamentos>
        <departamento>
            <nombre>Zapatillas</nombre>
        </departamento>
        <departamento comentario="sin encargado">
            <nombre>Guantes</nombre>
        </departamento>
    </departamentos>
    <productos>
        <producto id="p0015">
            <nombre>Zapatillas Trekking</nombre>
            <precio moneda="euros" descuento="si">30.50</precio>
        </producto>
        <producto id="p0016">
            <nombre>Zapatillas Basquet</nombre>
            <precio moneda="pesetas" descuento="si">25.95</precio>
        </producto>
        <producto id="p0045">
            <nombre>Guantes esqu√≠</nombre>
            <precio>16</precio>
        </producto>
    </productos>
</tienda>
