=== iamabhijeet2003/DAW/1-DAW/LMI/XSD/3.7/ejercicio7xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="oferta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"/>
                            <xs:element name="modelo" type="xs:string"/>
                            <xs:element name="motor" type="motorCaract"/>
                            <xs:element name="matricula" type="matriculaAnyo" />
                            <xs:element name="kilometros" type="xs:integer" />
                            <xs:element name="precio_inicial" type="xs:decimal"/>
                            <xs:element name="precio_oferta" type="xs:decimal"/>
                            <xs:element name="extras" type="extraCoche" maxOccurs="unbounded"/>
                            <xs:element name="fotos" type="fotoCoche" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="color" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="motorCaract">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="tipo" use="optional">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="diesel"/>
                            <xs:enumeration value="gasolina"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="matriculaAnyo">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="anyo" use="required" type="xs:gYear"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="extraCoche">
        <xs:sequence>
            <xs:element name="extra" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fotoCoche">
        <xs:sequence>
            <xs:element name="foto" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="tipoFoto" default="frontal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="frontal"/>
                                        <xs:enumeration value="trasera"/>
                                        <xs:enumeration value="lateral"/>
                                        <xs:enumeration value="interior"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== iamabhijeet2003/DAW/1-DAW/LMI/XSD/XSD3.7/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<oferta  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio7xsd.xsd">
    <vehiculo color="rojo">
        <marca>ford</marca>
        <modelo>focus</modelo>
        <motor tipo="diesel">duratore 1.4</motor>
        <matricula anyo="2014">1234AAAA</matricula>
        <kilometros>12500</kilometros>
        <precio_inicial>12000</precio_inicial>
        <precio_oferta>9999.95</precio_oferta>
        <extras>
            <extra>llantas</extra>
            <extra>pintura metalizada</extra>
        </extras>
        <fotos>
            <foto tipoFoto="frontal">11325.jpg</foto>
            <foto tipoFoto="interior">11326.jpg</foto>
            <foto>11345.jpg</foto>
        </fotos>
    </vehiculo>
    <vehiculo color="azul oscuro">
        <marca>ford</marca>
        <modelo>focus</modelo>
        <motor tipo="gasolina">duratore 2.0</motor>
        <matricula anyo="2015">12345AAA</matricula>
        <kilometros>125000</kilometros>
        <precio_inicial>10000</precio_inicial>
        <precio_oferta>9000</precio_oferta>
        <extras>
            <extra>pintura metalizada</extra>
            <extra>spoiler trasero</extra>
            <extra>climatizador</extra>
        </extras>
        <fotos>
            <foto tipoFoto="frontal">11345.jpg</foto>
        </fotos>
    </vehiculo>
</oferta>
