=== iamabhijeet2003/DAW/1-DAW/LMI/XML/examen/exercici4_abhijeet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="feed">
    <xs:complexType>

      <xs:sequence>
        
        <xs:element name="title" type="xs:string"/>

        <xs:element name="link">

          <xs:complexType>

            <xs:simpleContent>

              <xs:extension base="xs:string">

                <xs:attribute name="rel" type="xs:string" default="self" />

              </xs:extension>

            </xs:simpleContent>

          </xs:complexType>

        </xs:element>

        <xs:element name="updated" type="xs:dateTime"/>
        <xs:element name="author" type="xs:string"/>

        <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">

          <xs:complexType>

            <xs:sequence>

              <xs:element name="title">

                <xs:complexType>

                  <xs:simpleContent>

                    <xs:extension base="xs:string">

                      <xs:attribute name="id" type="xs:integer" use="optional"/>

                    </xs:extension>

                  </xs:simpleContent>

                </xs:complexType>

              </xs:element>

              <xs:element name="summary" type="xs:string"/>

            </xs:sequence>

          </xs:complexType>

        </xs:element>

      </xs:sequence>

    </xs:complexType>
  </xs:element>

</xs:schema>

=== iamabhijeet2003/DAW/1-DAW/LMI/XML/examen/exercisi4_abhijeet.xml
<?xml version="1.0" encoding="UTF-8"?>
< xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="exercici4_abhijeet.xsd">
<feed>
    <title>RSS de noticias de portada</title>
    <link rel="self">http://www.eldiariomontanes.es/rss/atom/portada</link>
    <updated>2017-12-06T13:43:23+01:00</updated>
    <author>portada</author>
    <entry>
            <title id="20171206132009"> <![CDATA[ Gorostiaga defiende una reforma constitucional amplia y no limitada al modelo territorial ]]> </title>
            <summary> <![CDATA[ La presidenta del Parlamento muestra su preocupación por el desprecio con el que algunos hablan de la Carta Magna durante la celebración de su 39 aniversario ]]> </summary>
     </entry>
     <entry>
            <title id="20171206202455"><![CDATA[ La estafa piramidal con cupones descuento de Groupalia llega a Cantabria ]]></title>
            <summary><![CDATA[ Empresarios de la región que tenían acuerdos con esta firma denuncian que acumulan facturas sin pagar por valor cercano a los 23.000 euros ]]></summary>
        </entry>
</feed>
