=== iamabhijeet2003/DAW/1-DAW/LMI/DTD/practica3.5/ejercicio6.dtd
<!ELEMENT tienda (departamentos, productos)>
    <!ELEMENT departamentos (departamento+)>
    <!ELEMENT departamento (nombre)>
    <!ATTLIST departamento id ID #REQUIRED
                             comentario CDATA #IMPLIED>
    <!ELEMENT productos (producto+)>
    <!ELEMENT producto (nombre, precio)>
    <!ATTLIST producto id ID #REQUIRED
        idDepartamento IDREF #REQUIRED
        comentario CDATA #IMPLIED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio moneda CDATA #IMPLIED
                     descuento (si|no) "no">

=== iamabhijeet2003/DAW/1-DAW/LMI/DTD/practica3.5/ejercicio6.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tienda SYSTEM "ejercicio6.dtd">
<tienda>
      <departamentos>
            <departamento id="d01">
                  <nombre>Zapatillas</nombre>
            </departamento>
            <departamento id="d02" comentario="sin encargado">
                  <nombre>Guantes</nombre>
            </departamento>
      </departamentos>
      <productos>
            <producto id="p0015" idDepartamento="d01">
                  <nombre>Zapatillas Trekking</nombre>
                  <precio moneda="euros" descuento="si">30</precio>
            </producto>
            <producto id="p0016" idDepartamento="d01">
                  <nombre>Zapatillas Basquet</nombre>
                  <precio moneda="pesetas" descuento="si">25</precio>
            </producto>
            <producto id="p0045" idDepartamento="d02" comentario="sin stock">
                  <nombre>Guantes esquí</nombre>
                  <precio>16</precio>
            </producto>
      </productos>
</tienda>
