=== iamabhijeet2003/DAW/1-DAW/LMI/DTD/practica3.5/ejercicio5.dtd
<!ELEMENT rss (channel)>
    <!ATTLIST rss version CDATA "2.0">
    <!ELEMENT channel (title, description, link, image?, language?, item*)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT link (#PCDATA)>
    <!ELEMENT image (url, title, link)>
    <!ELEMENT url (#PCDATA)>
    <!ELEMENT language (#PCDATA)>
    <!ELEMENT item (title, description, link?, guid?, pubDate?, enclosure?)>
    <!ELEMENT guid (#PCDATA)>
    <!ATTLIST guid isPermaLink CDATA "false">
    <!ELEMENT pubDate (#PCDATA)>
    <!ELEMENT enclosure EMPTY>
    <!ATTLIST enclosure length CDATA #REQUIRED
                         type CDATA #REQUIRED
                         url CDATA #REQUIRED>

=== iamabhijeet2003/DAW/1-DAW/LMI/DTD/practica3.5/ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rss SYSTEM "ejercicio5.dtd">
<rss version="2.0">
    <channel>
        <title><![CDATA[BBC Mundo - Noticias]]></title>
        <description><![CDATA[BBC Mundo - Noticias]]></description>
        <link>http://www.bbcmundo.com</link>
        <image>
            <url>http://www.bbc.co.uk/mundo/images/gel/rss_logo.gif</url>
            <title>BBC Mundo - Noticias</title>
            <link>http://www.bbcmundo.com</link>
        </image>
        <language>es</language>
        <item>
            <title><![CDATA[3 razones por las que Jerusalén es una ciudad sagrada para
judíos, musulmanes y cristianos]]></title>
            <description><![CDATA[El anuncio de que el presidente de Estados Unidos,
Donald Trump, reconocerá a Jerusalén como capital de Israel, ha provocado un incremento
de las tensiones en una de las regiones más conflictivas del mundo. Y es que para las
tres religiones monoteistas esta ciudad es uno de sus sitios más
sagrados.]]></description>
            <link>http://www.bbc.com/mundo/noticias-internacional-42251691</link>
            <guid isPermaLink="true">http://www.bbc.com/mundo/noticias-internacional-
42251691</guid>
            <pubDate>Wed, 06 Dec 2017 13:37:01 GMT</pubDate>
            <enclosure length="16481" type="image/jpeg"
url="http://news.bbcimg.co.uk/media/images/74156000/jpg/_74156332_jerusalem2.jpg"/>
        </item>
        <item>
            <title><![CDATA[6 cosas envidiables y 3 curiosidades de Finlandia a 100 años
de su independencia (y el dato de por qué son los reyes del sauna)]]></title>
            <description><![CDATA[Los finlandeses nos dieron el inolvidable Nokia 1100,
el adictivo pero no tan memorable Angry Birds, y el emblemático (y vandálico) cóctel
molotov. Y bastante más. BBC Mundo te cuenta detalles extraordinarios de este país
nórdico que celebra su centenario.]]></description>
            <link>http://www.bbc.com/mundo/noticias-internacional-42237724</link>
            <guid isPermaLink="true">http://www.bbc.com/mundo/noticias-internacional-
42237724</guid>
            <pubDate>Wed, 06 Dec 2017 05:10:01 GMT</pubDate>
            <enclosure length="47568" type="image/jpeg"
url="http://c.files.bbci.co.uk/91CF/production/_99072373_gettyimages-634710858.jpg"/>
        </item>
   </channel>
</rss>
